micronaut:
  application:
    name: vendor
  server:
       max-request-size: '500MB'
       multipart:
           max-file-size: '500MB'
       cors:
            enabled: true
datasources:
  default:
    url: jdbc:sqlserver://localhost:1433;databaseName=Vendor
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: Anemoi
    password: Anemoi@123
    
    schema-generate: CREATE_DROP
    dialect: SQL_SERVER
jpa.default.properties.hibernate.hbm2ddl.auto: update
netty:    
 jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true